["leONS"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

#[".config/zsh/plugins"]
#    type = "git-repo"
#    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
#    refreshPeriod = "672h"
