# TODO: Documentation
# desktop profiles implies core 'can not "use" firefox" if I don't get my CLI
# setup up and running

linux:
  profiles:
    core:
      - bat
      - curl
      - fzf
      - htop
      - neofetch
      - tmux
      - tree
      - vim
      - wget
      - zsh
      - zsh-syntax-highlighting

    # implies core
    desktop:
      - xorg
      - firefox

  debian:
    core:
      - build-essential
      - fd-find
      - universal-ctags
    desktop:
      - libx11-dev
      - libxft-dev
      - libxinerama-dev
      - fonts-noto-cjk

  void:
    core:
      - base-devel
      - fd
      - ctags
    desktop:
      - libX11-devel
      - libXft-devel
      - libXinerama-devel
      - noto-fonts-cjk

bsd:
  profiles:
    core:
      - htop
    desktop:
      - xorg
      - firefox
